name: Docker prod
on:
    push:
        branches: ['*']
    pull_request:
        branches: ['*']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup dependencies
      run: |
          pip3 install -r services/web/requirements.txt
    - name: docker
      run: |
        git submodule init
        git submodule update
        docker-compose -f docker-compose.prod.yml up -d --build
        docker ps -a
        sleep 20
        # load data test
        # sh load_parallel.sh
        # docker-compose exec -T pg_normalized ./run_tests.sh
